backend:
  name: github
  repo: Teens-in-AI/tech-week
#publish_mode: editorial_workflow
media_folder: "docs/images"
public_folder: "hackathon-guide/images"
collections:
  - name: "doc"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
